# Generated by Django 5.1.4 on 2025-01-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_annualincome_education_employment_groombrideinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=255)),
                ('number_of_brothers', models.PositiveIntegerField(default=0)),
                ('number_of_sisters', models.PositiveIntegerField(default=0)),
                ('married_brothers', models.PositiveIntegerField(default=0)),
                ('married_sisters', models.PositiveIntegerField(default=0)),
                ('family_description', models.TextField(blank=True, null=True)),
                ('family_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.familystatus')),
                ('family_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.familytype')),
                ('father_occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_occupations', to='authentication.occupation')),
                ('mother_occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_occupations', to='authentication.occupation')),
            ],
        ),
    ]
