# Generated by Django 5.1.4 on 2025-01-15 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_familystatus_familytype_occupation_familyinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyinformation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
