# Generated by Django 5.1.4 on 2025-01-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_familyinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groombrideinfo',
            name='family_live',
            field=models.BooleanField(default=False),
        ),
    ]
