# Generated by Django 5.1.4 on 2025-01-15 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_groombrideinfo_family_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groombrideinfo',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.occupation'),
        ),
    ]
