# Generated by Django 5.1.4 on 2025-01-15 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_groombrideinfo_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('otp_sent', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('identity_proof_image', models.ImageField(blank=True, null=True, upload_to='identity_proofs/')),
                ('aadhar_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
