# Generated by Django 5.1.4 on 2025-01-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Created For')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='createfor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.createfor', verbose_name='Created For'),
        ),
    ]
