# Generated by Django 5.1.4 on 2025-01-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
