# Generated by Django 5.1.4 on 2025-01-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_rename_preference_drinkingpreference_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maritalstatus',
            old_name='name',
            new_name='status',
        ),
    ]
