# Generated by Django 5.1.4 on 2025-01-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_rename_name_maritalstatus_status'),
        ('partnerpreferences', '0003_remove_partnerexpectation_language_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MotherTongue',
        ),
    ]
