# Generated by Django 5.1.4 on 2025-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_profile_mother_tongue_delete_mothertongue'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
