# Generated by Django 5.1.4 on 2025-01-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_profile_languages_spoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='groombrideinfo',
            name='addres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groombrideinfo',
            name='present_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groombrideinfo',
            name='present_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groombrideinfo',
            name='present_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groombrideinfo',
            name='secondary_mobileno',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Secondary Mobile Number'),
        ),
        migrations.AddField(
            model_name='groombrideinfo',
            name='time_to_call',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
