# Generated by Django 5.1.4 on 2025-02-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_groombrideinfo_addres_groombrideinfo_present_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groombrideinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
