# Generated by Django 5.1.4 on 2025-02-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_interestsent_timestamp_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyinformation',
            name='mother_name',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
