# Generated by Django 5.1.4 on 2025-02-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_familyinformation_mother_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='physical_status',
        ),
    ]
