# Generated by Django 5.1.4 on 2025-02-20 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_remove_profile_physical_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='physical_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.physicalstatus'),
        ),
    ]
