# Generated by Django 5.1.4 on 2025-03-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message Notification'), ('interest', 'Interest Notification')], default='message', max_length=20),
        ),
    ]
