# Generated by Django 5.1.4 on 2025-03-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_user_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
