# Generated by Django 5.1.4 on 2025-03-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobileno',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Mobile Number'),
        ),
    ]
