# Generated by Django 5.1.4 on 2025-03-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('customer', 'Customer')], default='', max_length=20, verbose_name='User Type'),
        ),
    ]
