# Generated by Django 5.1.4 on 2025-03-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0042_user_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userverification',
            old_name='aadhar_verified',
            new_name='proof_verified',
        ),
    ]
