# Generated by Django 5.1.4 on 2025-03-26 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0043_rename_aadhar_verified_userverification_proof_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverification',
            name='identity_proof_image',
        ),
        migrations.CreateModel(
            name='IdentityProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='identity_proofs/')),
                ('user_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_proofs', to='authentication.userverification')),
            ],
        ),
    ]
