# Generated by Django 5.1.4 on 2025-03-27 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_remove_userverification_identity_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 27, 12, 0)),
            preserve_default=False,
        ),
    ]
