# Generated by Django 5.1.4 on 2025-01-29 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0017_drinkingpreference_ethnicgroup_physicalstatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_preference', models.CharField(default='Does not matter', max_length=50)),
                ('height_preference', models.CharField(default='Does not matter', max_length=50)),
                ('partner_district', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_country', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_income', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.annualincome')),
                ('drinking_preference', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.drinkingpreference')),
                ('education', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.education')),
                ('ethnic_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.ethnicgroup')),
                ('language_preference', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.mothertongue')),
                ('marital_status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.maritalstatus')),
                ('physical_status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.physicalstatus')),
                ('profession', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.employment')),
                ('smoking_preference', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.smokingpreference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_expectation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
