# Generated by Django 5.1.4 on 2025-01-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerpreferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerexpectation',
            name='ethnic_group',
        ),
    ]
