# Generated by Django 5.1.4 on 2025-01-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerpreferences', '0002_remove_partnerexpectation_ethnic_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerexpectation',
            name='language_preference',
        ),
        migrations.AddField(
            model_name='partnerexpectation',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
