# Generated by Django 5.1.4 on 2025-02-02 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_blood_hair_hairtype_political_polygamy_religiousness_and_more'),
        ('partnerpreferences', '0003_remove_partnerexpectation_language_preference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CookingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EatingHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets_details', models.TextField(blank=True, null=True)),
                ('favourite_sports', models.TextField(blank=True, null=True)),
                ('favourite_places', models.TextField(blank=True, null=True)),
                ('favourite_books', models.TextField(blank=True, null=True)),
                ('movies_and_music', models.TextField(blank=True, null=True)),
                ('dress_sense', models.TextField(blank=True, null=True)),
                ('body_art', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerpreferences.bodyart')),
                ('cooking_skill', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerpreferences.cookingskill')),
                ('drinking_habits', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.drinkingpreference')),
                ('eating_habits', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerpreferences.eatinghabit')),
                ('exercise', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerpreferences.exercise')),
                ('smoking_habits', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.smokingpreference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
