# Generated by Django 5.1.4 on 2025-02-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerpreferences', '0004_bodyart_cookingskill_eatinghabit_exercise_userhobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerexpectation',
            name='age_preference',
            field=models.CharField(blank=True, default='Does not matter', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerexpectation',
            name='height_preference',
            field=models.CharField(blank=True, default='Does not matter', max_length=50),
        ),
    ]
