# Generated by Django 5.1.4 on 2025-02-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_familyinformation_mother_name'),
        ('partnerpreferences', '0005_alter_partnerexpectation_age_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerexpectation',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='partnerexpectation',
            name='marital_status',
            field=models.ManyToManyField(blank=True, to='authentication.maritalstatus'),
        ),
    ]
