# Generated by Django 5.1.4 on 2025-02-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_familyinformation_mother_name'),
        ('partnerpreferences', '0006_remove_partnerexpectation_marital_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerexpectation',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='partnerexpectation',
            name='drinking_preference',
        ),
        migrations.RemoveField(
            model_name='partnerexpectation',
            name='education',
        ),
        migrations.RemoveField(
            model_name='partnerexpectation',
            name='physical_status',
        ),
        migrations.RemoveField(
            model_name='partnerexpectation',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='partnerexpectation',
            name='smoking_preference',
        ),
        migrations.AddField(
            model_name='partnerexpectation',
            name='annual_income',
            field=models.ManyToManyField(blank=True, to='authentication.annualincome'),
        ),
        migrations.AddField(
            model_name='partnerexpectation',
            name='drinking_preference',
            field=models.ManyToManyField(blank=True, to='authentication.drinkingpreference'),
        ),
        migrations.AddField(
            model_name='partnerexpectation',
            name='education',
            field=models.ManyToManyField(blank=True, to='authentication.education'),
        ),
        migrations.AddField(
            model_name='partnerexpectation',
            name='physical_status',
            field=models.ManyToManyField(blank=True, to='authentication.physicalstatus'),
        ),
        migrations.AddField(
            model_name='partnerexpectation',
            name='profession',
            field=models.ManyToManyField(blank=True, to='authentication.employment'),
        ),
        migrations.AddField(
            model_name='partnerexpectation',
            name='smoking_preference',
            field=models.ManyToManyField(blank=True, to='authentication.smokingpreference'),
        ),
    ]
