# Generated by Django 5.1.4 on 2025-03-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socketconnection', '0003_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
