# Generated by Django 5.1.4 on 2025-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socketconnection', '0005_rename_content_message_message_remove_message_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio_messages/'),
        ),
    ]
